document.getElementById("menubar").innerHTML=
'<div id="hormenu">'
+		'<ul>'
+			'<li><a href="index.html">La Compagnie</a>'
+				'<ul>'
+				'<li><a href="#">Présentation générale</a></li>'
+				'</ul>'
+          '</li>'
+			'<li><a href="#">Les Créations</a>'
+                '<ul>'
+                '<li><a href="#">La Déferle</a></li>'
+				'<li><a href="#">Presqu’Illisible</a></li>'
+				'<li><a href="#">Le Carrousel du Flare</a></li>'
+				'<li><a href="#">Ancrage</a></li>'
+				'<li><a href="#">Le Clown lunatique et la Danseuse étoile</a></li>'
+				'</ul> '
+			'</li>'
+			'<li><a href="#">Les Ateliers</a>'
+				'<ul>' 
+				'<li><a href="#">Jeux de rôles et de rêves</a></li>'
+				'</ul>'
+			'</li>'
+			'<li><a href="#">Médiations culturelles</a>'
+				'<ul> '
+				'<li><a href="#">La Déferle</a></li>'
+				'</ul>'
+			'</li>'
+     	'</ul>'
+ '</div>'

