document.getElementById("menubar").innerHTML=
'<div id="hormenu">'
+		'<ul>'
+			'<li><a href="index.html">La Compagnie</a>'
+				'<ul>'
+				'<li><a href="index.html">Présentation générale</a></li>'
+				'<li><a href="#">Équipage artistique</a></li>'
+       '<li><a href="#">Actualités</a></li>'
+				'</ul>'
+          '</li>'
+			'<li><a href="#">Les Créations</a>'
+                '<ul>'
+                '<li><a href="#">La Déferle</a></li>'
+				'<li><a href="#">Presqu’Illisible</a></li>'
+				'<li><a href="#">Le Carrousel du Flare</a></li>'
+				'<li><a href="#">Ancrage</a></li>'
+				'<li><a href="#">Le Clown lunatique et la Danseuse étoile</a></li>'
+				'</ul> '
+			'</li>'
+			'<li><a href="#">Les Ateliers</a>'
+				'<ul>'
+				'<li><a href="#">Jeux de rôles et de rêves</a></li>'
+				'<li><a href="#">Ateliers Théâtre</a></li>'
+				'<li><a href="#">Ateliers mécano-dactylographiques</a></li>'
+				'<li><a href="#">Ateliers incarnés</a></li>'
+				'<li><a href="#">Au long cours</a></li>'
+				'</ul>'
+			'</li>'
+			'<li><a href="#">Médiations culturelles</a>'
+				'<ul> '
+				'<li><a href="#">Zone Bleue</a></li>'
+				'<li><a href="#">En épistolaire</a></li>'
+				'<li><a href="#">MatchEs</a></li>'
+				'</ul>'
+			'</li>'
+     	'</ul>'
+ '</div>'
