document.getElementById("menubar").innerHTML=
'<div id="hormenu">'
+		'<ul>'
+			'<li><a href="index.html">La Compagnie</a>'
+				'<ul>'
+				'<li><a href="index.html">Lunée l’Ôtre</a></li>'
+				'<li><a href="#">L’Équipage</a></li>'
+				'</ul>'
+          '</li>'
+			'<li><a href="#">Les Créations</a>'
+                '<ul>'
+                '<li><a href="LaDeferle.html">La Déferle</a></li>'
+				'<li><a href="PresquIllisible.html">Presqu’Illisible</a></li>'
+				'<li><a href="LeCarrouselDuFlare">Le Carrousel du Flare</a></li>'
+				'<li><a href="#">Ancrage</a></li>'
+				'<li><a href="#">Le Clown lunatique et la Danseuse étoile</a></li>'
+				'</ul> '
+			'</li>'
+			'<li><a href="#">Les Ateliers</a>'
+				'<ul>'
+				'<li><a href="#">Jeux de rôles et de rêves</a></li>'
+				'<li><a href="#">Ateliers Théâtre</a></li>'
+				'<li><a href="#">Ateliers d’écriture</a></li>'
+				'<li><a href="#">Paysages et Musées</a></li>'
+				'<li><a href="#">Au long cours</a></li>'
+				'</ul>'
+			'</li>'
+			'<li><a href="#">Sur le terrain</a>'
+				'<ul> '
+				'<li><a href="#">Zone Bleue</a></li>'
+				'<li><a href="#">En épistolaire</a></li>'
+				'<li><a href="#">MatchEs</a></li>'
+				'</ul>'
+			'</li>'
+       '<li><a href="#">Journal de bord</a></li>'
+     	'</ul>'
+ '</div>'
